### ISSUE TITLE
Discussion about this project

### ISSUE THREAD

**Issue by JianyuanYin** [sherryzyh/mtcnn-tf-plate-detection#1]
hello!
Our team need to apply MTCNN to our project.
I have used the code in your references. Although it has many stars, it's difficult to use especially in prepare data.
Many thanks,  you have written .sh to make it easy.
I have some questions before using this code, thanks again.
1、whether the model can be used in C++ easily?
2、can I use wider face for pre-train, and use my data for transfer by only using runMy.sh?
3、whether this code can integrate the three models(P、R、O) into one model?
4、Is the gpu utilized fully for that the code in your references is too slow. The nms consume lots of time.

**Comment by JianyuanYin** [comment]
5、and the results on FDDB and the test speed, thanks

**Comment by sherryzyh** [comment]
Hi! Thanks for your comment.
I can answer some of your questions as follows.
1. Sorry, I am not working on it now.
2. I am working on adapting the MTCNN to plates detection. So, runMy.sh is now specifically used for customized plates dataset(with 4 landmarks). I think you should check the code carefully.
3. According to the MTCNN algorithm, I don't think so.
4. I am not sure about your question. I don't set things like "config.gpu_options.per_process_gpu_memory_fraction = 0.x" if you mean so.
